### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by bobhenl** [Zrips/TryMe#31]
```
[15:18:43 ERROR]: Could not pass event BlockPlaceEvent to TryMe v7.2.0.0
java.lang.ClassCastException: class me.Zrips.TryMe.Constructors.EntityAnswer cannot be cast to class me.Zrips.TryMe.Constructors.MaterialAnswer (me.Zrips.TryMe.Constructors.EntityAnswer and me.Zrips.TryMe.Constructors.MaterialAnswer are in unnamed module of loader 'TryMe7.1.2.0.jar' @5f71a394)
        at me.Zrips.TryMe.gameModes.PlaceMode.checkConsumed(PlaceMode.java:54) ~[TryMe7.1.2.0.jar:?]
        at me.Zrips.TryMe.gameModes.PModeListener.onPlayerItemConsumeEvent(PModeListener.java:33) ~[TryMe7.1.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1754.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:446) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:419) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:602) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2098) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

**Comment by TeamHRLive** [comment]
Same error on 1.20.4
Spams every time someone breaks a block no matter if Block Tracking Event is going on or not.

**Comment by TeamHRLive** [comment]
[03:11:10 ERROR]: Could not pass event PlayerItemConsumeEvent to TryMe v7.2.0.0
java.lang.ClassCastException: class me.Zrips.TryMe.Constructors.StringAnswer cannot be cast to class me.Zrips.TryMe.Constructors.MaterialAnswer (me.Zrips.TryMe.Constructors.StringAnswer and me.Zrips.TryMe.Constructors.MaterialAnswer are in unnamed module of loader 'TryMe7.1.2.0.jar' @3ca4c027)
        at me.Zrips.TryMe.gameModes.EatMode.checkConsumed(EatMode.java:55) ~[TryMe7.1.2.0.jar:?]
        at me.Zrips.TryMe.gameModes.EModeListener.onPlayerItemConsumeEvent(EModeListener.java:39) ~[TryMe7.1.2.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1103.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:git-Purpur-2133]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.LivingEntity.completeUsingItem(LivingEntity.java:4136) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.completeUsingItem(ServerPlayer.java:1959) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updateUsingItem(LivingEntity.java:3996) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.updateUsingItem(ServerPlayer.java:2649) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.updatingUsingItem(LivingEntity.java:3976) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3095) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:299) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:789) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:353) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1772) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1549) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1237) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.20.4.jar:git-Purpur-2133]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Zrips** [comment]
Should be fixed with next update
